d3safio/config/routes.rb
Rails.application.routes.draw do
  resources :order_products
  resources :products
  resources :orders
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

d3safio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <style>
    body{
        margin: 0;
        background-color: #333333;
    }

    h1{
        padding: 0;
        margin: 0;
        border: 0;
    }
    header{
        position: relative;
        top: 0;
        background-color: #4DDBAA ;
        width: 100%;


    }
    a:link, a:visited {
        background-color: #4DDBAA;
        border: solid 1px #333333;
        color: white;
        padding: 14px 25px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
    }

    a:hover, a:active {
        background-color: red;
    }
  </style>
  <head>
    <title>D3safio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header>
    <h1>M K A R T</h1>
    <nav>
      <%= link_to 'Usuários', people_path %>
      <%= link_to 'Carrinho', orders_path %>
      <%= link_to 'Produtos', products_path %>
      <%= link_to 'Pedidos', order_products_path %>
    </nav>
  </header>
  <corpo>

    <%= yield %>
  </corpo>

  <footer>

  </footer>
  </body>
</html>