d3safio/config/routes.rb
Rails.application.routes.draw do
  resources :order_products
  resources :products
  resources :orders
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

d3safio/app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

d3safio/app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
  before_action :set_order_product, only: %i[ show edit update destroy ]

  # GET /order_products or /order_products.json
  def index
    @order_products = OrderProduct.all
  end

  # GET /order_products/1 or /order_products/1.json
  def show
  end

  # GET /order_products/new
  def new
    @order_product = OrderProduct.new
  end

  # GET /order_products/1/edit
  def edit
  end

  # POST /order_products or /order_products.json
  def create
    @order_product = OrderProduct.new(order_product_params)

    respond_to do |format|
      if @order_product.save
        format.html { redirect_to @order_product, notice: "Order product was successfully created." }
        format.json { render :show, status: :created, location: @order_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_products/1 or /order_products/1.json
  def update
    respond_to do |format|
      if @order_product.update(order_product_params)
        format.html { redirect_to @order_product, notice: "Order product was successfully updated." }
        format.json { render :show, status: :ok, location: @order_product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_products/1 or /order_products/1.json
  def destroy
    @order_product.destroy
    respond_to do |format|
      format.html { redirect_to order_products_url, notice: "Order product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_product
      @order_product = OrderProduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_product_params
      params.require(:order_product).permit(:name, :order_id, :product_id, :quantity)
    end
end

d3safio/app/helpers/order_products_helper.rb
module OrderProductsHelper
end

d3safio/app/views/order_products/_form.html.erb
<%= form_with(model: order_product, local: true) do |form| %>
  <% if order_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_product.errors.count, "error") %> prohibited this order_product from being saved:</h2>

      <ul>
      <% order_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.collection_select :order_id, Order.order(:name),:id,:id, {include_blank: false },class:"form-select",placeholder:"Nome da compra"  %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.collection_select :product_id, Product.order(:name),:id,:name, {include_blank: false },class:"form-select",placeholder:"Nome da compra"  %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, min: 1 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

d3safio/app/views/order_products/edit.html.erb
<h1>Editing Order Product</h1>

<%= render 'form', order_product: @order_product %>

<%= link_to 'Show', @order_product %> |
<%= link_to 'Back', order_products_path %>

d3safio/app/views/order_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Order</th>
      <th>Product</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_products.each do |order_product| %>
      <tr>
        <td><%= order_product.name %></td>
        <td><%= order_product.order.id %></td>
        <td><%= order_product.product.name %></td>
        <td><%= order_product.quantity %></td>
        <td><%= link_to 'Show', order_product %></td>
        <td><%= link_to 'Edit', edit_order_product_path(order_product) %></td>
        <td><%= link_to 'Destroy', order_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Product', new_order_product_path %>

d3safio/app/views/order_products/new.html.erb
<h1>New Order Product</h1>

<%= render 'form', order_product: @order_product %>

<%= link_to 'Back', order_products_path %>

d3safio/app/views/order_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order_product.name %>
</p>

<p>
  <strong>Order:</strong>
  <%= "#{ @order_product.order.name} #{@order_product.order.person.name}" %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order_product.product.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_product.quantity %>
</p>

<%= link_to 'Edit', edit_order_product_path(@order_product) %> |
<%= link_to 'Back', order_products_path %>